spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER_NAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER}