spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://reminderapp-mysql:3306/reminderDB
    username: secret
    password: secretpassword
    driver-class-name: com.mysql.cj.jdbc.Driver