version: '3.4'

services:
  backend:
    image: amazeus-backend-debug
    build:
      context: backend
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8000"]
    ports:
      - 8000:8000
      - 5678:5678

  frontend:
    image: amazeus-frontend
    build:
      context: frontend
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080