From python:latest

ADD stage2 /
WORKDIR stage2


#COPY requirements.txt ./
#RUN pip install --no-cache-dir -r requirements.txt


CMD [ "python", "./stage2.py" ]


ENTRYPOINT ["python", "./stage2.py"]


