version: '3.8'
services:
  # * DATABASE
  mysql_db:
    container_name: mysql_db
    image: mysql/mysql-server:8.0.29
    volumes:
      - ./volume/db_data/:/var/lib/mysql
      - ./volume/db_init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  # * API
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./volume/config/:/opt/app/volume/config
    depends_on:
      - mysql_db
    ports:
      - 5000:5000
    command: [ --config, volume/config/flask_production.yml, --host, api, --port, '5000' ]
