@host = 0.0.0.0
@port = 5000
@socket = {{host}}:{{port}}
@content_type = application/json

@prefix = api/v1

### * TEST
GET http://{{socket}}/

### ? BUS ##################################
### GET BUS BY ID
GET http://{{socket}}/{{prefix}}/bus/1

### CREATE BUS
POST http://{{socket}}/{{prefix}}/bus
Content-Type: {{content_type}}

{
    "model": "C0",
    "make": "BMW"
}

### ? DRIVER ###############################
### GET DRIVER BY ID
GET http://{{socket}}/{{prefix}}/driver/1

### GET TOP N DRIVERS
GET http://{{socket}}/{{prefix}}/driver/top/5
    ?from=2022-01-01 00:00
    &to=2022-02-03 00:00
    # &page=1
    # &per_page=2

### CREATE DRIVER
POST http://{{socket}}/{{prefix}}/driver
Content-Type: {{content_type}}

{
    "first_name": "Ray",
    "last_name": "Sheha",
    "email": "ray@mondo.ca",
    "social_security_number": 1234567890
}

### ? SCHEDULE #############################
### GET SCHEDULE BY ID
GET http://{{socket}}/{{prefix}}/schedule/3

### GET SCHEDULE BY BUS_ID, DRIVER_ID, WEEK
GET http://{{socket}}/{{prefix}}/schedule
    ?from=2022-01-01 00:00
    &to=2022-12-03 00:00
    &driver_id=2
    # &bus_id=2
    # &page=1
    # &per_page=2

### CREATE SCHEDULE
POST http://{{socket}}/{{prefix}}/schedule
Content-Type: {{content_type}}

{
    "bus_id": 2,
    "driver_id": 7,
    "dt_start": "2022-01-02 12:21",
    "dt_end": "2022-02-02 10:02"
}

### ! AVAILABLE SCHEDULE ###################
### GET ALL AVAILABLE SCHEDULES
GET http://{{socket}}/{{prefix}}/available_schedule
    ?page=3
    &per_page=5
    &driver_id=3
