spring:
  application:
    name: bus

  ###### kafka ######
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
    listener:
      missing-topics-fatal: false

  ###### database ######
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: dbuser
    password: dbpass
    driver-class-name: org.postgresql.Driver

  ###### spring security ######
  security:
    user:
      name: user
      password: mypassword

###### HTTP Server ######
server:
  port: 8080
  max-http-header-size: 65536
  error:
    whitelabel:
      enabled: true
    include-message: always


###### Logger ######
logging:
  level:
    root: info
    com:
      beyond:
        microservice:
          settings: info

