spring:
  application:
    name: bus-app
    external-context-path: /bus-app
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: supportmail@gmail.com
    password: password
    properties:
      mail:
        debug: true
        smtp:
          starttls:
            enabled: true
            required: true
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /bus-app

springdoc:
  api-doc:
    path: /api-doc
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui