spring:
  application:
    name: bus-app
    external-context-path: /bus-app
  profiles:
    active: h2

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:bus-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /bus-app