Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.4"
  config.vm.provision "shell", path: "vagrant_setup.sh"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
end
