-- view : views.VIEW_PIONEER
-- replace foreign key by USER_APPLICATION values
CREATE OR REPLACE VIEW views.VIEW_PIONEER AS
SELECT public.PIONEER.PIONEER_ID, public.PIONEER.PIONEER_LOGIN, public.PIONEER.PIONEER_PASSWORD, public.PIONEER.PIONEER_EMAIL, public.PIONEER.PIONEER_FIRST_NAME, public.PIONEER.PIONEER_LAST_NAME, public.PIONEER.PIONEER_BIRTHDATE, public.PIONEER.PIONEER_SEX, public.PIONEER.PIONEER_NOTATION, public.USER_APPLICATION.USER_APPLICATION_ID, public.USER_APPLICATION.USER_APPLICATION_PROFILE
FROM public.PIONEER, public.USER_APPLICATION
WHERE public.PIONEER.USER_APPLICATION_ID = public.USER_APPLICATION.USER_APPLICATION_ID;

-- view : views.VIEW_BABY_PARENT
-- replace foreign key by PIONEER values AND by the BABY_REQUEST values
CREATE OR REPLACE VIEW views.VIEW_BABY_PARENT AS
SELECT public.BABY_PARENT.BABY_PARENT_ID, public.PIONEER.PIONEER_ID, public.PIONEER.PIONEER_LOGIN, public.PIONEER.PIONEER_PASSWORD, public.PIONEER.PIONEER_EMAIL, public.PIONEER.PIONEER_FIRST_NAME, public.PIONEER.PIONEER_LAST_NAME, public.PIONEER.PIONEER_BIRTHDATE, public.PIONEER.PIONEER_SEX, public.PIONEER.PIONEER_NOTATION, public.BABY_REQUEST.REQUEST_ID, public.BABY_REQUEST.REQUEST_CREATE_DATE, public.BABY_REQUEST.REQUEST_SUBMIT_DATE, public.BABY_REQUEST.REQUEST_ACCEPT_DATE_1, public.BABY_REQUEST.REQUEST_ACCEPT_DATE_2, public.BABY_REQUEST.REQUEST_REFUSE_DATE_1, public.BABY_REQUEST.REQUEST_REFUSE_DATE_2, public.BABY_REQUEST.REQUEST_SCHEDULE_DATE, public.BABY_REQUEST.REQUEST_CLOSE_DATE, public.BABY_REQUEST.BABY_LOGIN, public.BABY_REQUEST.BABY_PASSWORD, public.BABY_REQUEST.BABY_EMAIL, public.BABY_REQUEST.BABY_FIRST_NAME, public.BABY_REQUEST.BABY_LAST_NAME, public.BABY_REQUEST.BABY_SEX
FROM public.BABY_PARENT, public.PIONEER, public.BABY_REQUEST
WHERE public.BABY_PARENT.PIONEER_ID = public.PIONEER.PIONEER_ID AND public.BABY_PARENT.REQUEST_ID = public.BABY_REQUEST.REQUEST_ID;

-- view : views.VIEW_BABY_CHECKERS
-- replace foreign key by PIONEER values AND by the BABY_REQUEST values
CREATE OR REPLACE VIEW views.VIEW_BABY_CHECKERS AS
SELECT public.BABY_CHECKERS.BABY_CHECKERS_ID, 
public.PIONEER.PIONEER_ID, public.PIONEER.PIONEER_LOGIN, public.PIONEER.PIONEER_PASSWORD, public.PIONEER.PIONEER_EMAIL, public.PIONEER.PIONEER_FIRST_NAME, public.PIONEER.PIONEER_LAST_NAME, public.PIONEER.PIONEER_BIRTHDATE, public.PIONEER.PIONEER_SEX, public.PIONEER.PIONEER_NOTATION, 
public.BABY_REQUEST.REQUEST_ID, public.BABY_REQUEST.REQUEST_CREATE_DATE, public.BABY_REQUEST.REQUEST_SUBMIT_DATE, public.BABY_REQUEST.REQUEST_ACCEPT_DATE_1, public.BABY_REQUEST.REQUEST_ACCEPT_DATE_2, public.BABY_REQUEST.REQUEST_REFUSE_DATE_1, public.BABY_REQUEST.REQUEST_REFUSE_DATE_2, public.BABY_REQUEST.REQUEST_SCHEDULE_DATE, public.BABY_REQUEST.REQUEST_CLOSE_DATE, public.BABY_REQUEST.BABY_LOGIN, public.BABY_REQUEST.BABY_PASSWORD, public.BABY_REQUEST.BABY_EMAIL, public.BABY_REQUEST.BABY_FIRST_NAME, public.BABY_REQUEST.BABY_LAST_NAME, public.BABY_REQUEST.BABY_SEX
FROM public.BABY_CHECKERS, public.PIONEER, public.BABY_REQUEST
WHERE public.BABY_CHECKERS.PIONEER_ID = public.PIONEER.PIONEER_ID AND public.BABY_CHECKERS.REQUEST_ID = public.BABY_REQUEST.REQUEST_ID;