-- table : BABY_CHECKERS
-- deletes
DELETE FROM public.BABY_CHECKERS WHERE BABY_CHECKERS_ID = 0;
DELETE FROM public.BABY_CHECKERS WHERE BABY_CHECKERS_ID = 1;
DELETE FROM public.BABY_CHECKERS WHERE BABY_CHECKERS_ID = 2;
DELETE FROM public.BABY_CHECKERS WHERE BABY_CHECKERS_ID = 3;
DELETE FROM public.BABY_CHECKERS WHERE BABY_CHECKERS_ID = 4;

-- table : BABY_PARENT
-- deletes
DELETE FROM public.BABY_PARENT WHERE BABY_PARENT_ID = 0;
DELETE FROM public.BABY_PARENT WHERE BABY_PARENT_ID = 1;
DELETE FROM public.BABY_PARENT WHERE BABY_PARENT_ID = 2;
DELETE FROM public.BABY_PARENT WHERE BABY_PARENT_ID = 3;

-- table : BABY_REQUEST
-- deletes
DELETE FROM public.BABY_REQUEST WHERE REQUEST_ID = 0;
DELETE FROM public.BABY_REQUEST WHERE REQUEST_ID = 1;
DELETE FROM public.BABY_REQUEST WHERE REQUEST_ID = 2;

-- table : PIONEER
-- deletes
DELETE FROM public.PIONEER WHERE PIONEER_ID = 0;
DELETE FROM public.PIONEER WHERE PIONEER_ID = 1;
DELETE FROM public.PIONEER WHERE PIONEER_ID = 2;
DELETE FROM public.PIONEER WHERE PIONEER_ID = 3;
DELETE FROM public.PIONEER WHERE PIONEER_ID = 4;
DELETE FROM public.PIONEER WHERE PIONEER_ID = 5;
DELETE FROM public.PIONEER WHERE PIONEER_ID = 6;
DELETE FROM public.PIONEER WHERE PIONEER_ID = 7;

-- table : USER_APPLICATION
-- deletes
DELETE FROM public.USER_APPLICATION WHERE USER_APPLICATION_ID = 0;
DELETE FROM public.USER_APPLICATION WHERE USER_APPLICATION_ID = 1;
DELETE FROM public.USER_APPLICATION WHERE USER_APPLICATION_ID = 2;
DELETE FROM public.USER_APPLICATION WHERE USER_APPLICATION_ID = 3;

-- table : RESOURCE_VARIATION
-- deletes
DELETE FROM public.RESOURCE_VARIATION WHERE RESOURCE_VARIATION_ID = 0;
DELETE FROM public.RESOURCE_VARIATION WHERE RESOURCE_VARIATION_ID = 1;
DELETE FROM public.RESOURCE_VARIATION WHERE RESOURCE_VARIATION_ID = 2;

-- table : RESOURCE 
-- deletes
DELETE FROM public.RESOURCE WHERE RESOURCE_ID = 0;
DELETE FROM public.RESOURCE WHERE RESOURCE_ID = 1;
DELETE FROM public.RESOURCE WHERE RESOURCE_ID = 2;

-- -----------------------------------------------------------------------------------------------------
-- DROP OF THE TABLES
DROP TABLE public.BABY_CHECKERS;
DROP TABLE public.BABY_PARENT;

DROP TABLE public.BABY_REQUEST;
DROP TABLE public.PIONEER;
DROP TABLE public.USER_APPLICATION;

DROP TABLE public.RESOURCE_VARIATION;
DROP TABLE public.RESOURCE;
DROP TABLE public.ELEMENT;

-- AUDITS
DROP TABLE audits.AUDIT_BABY_CHECKERS;
DROP TABLE audits.AUDIT_BABY_PARENT;

DROP TABLE audits.AUDIT_BABY_REQUEST;
DROP TABLE audits.AUDIT_PIONEER;
DROP TABLE audits.AUDIT_USER_APPLICATION;

DROP TABLE audits.AUDIT_RESOURCE_VARIATION;
DROP TABLE audits.AUDIT_RESOURCE;
DROP TABLE audits.AUDIT_ELEMENT;