
FLASK_ENV: development
SQLALCHEMY_DB_URI: mysql:///root:password@0.0.0.0/SCHEDULES
JWT_SECRET_KEY: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY1ODg4MTEyNiwiaWF0IjoxNjU4ODgxMTI2fQ.bhMyz1UCgvoO4YqsNGsP-vQlx7fUSgOVOaRRGyLZoGg'
