
FLASK_ENV: production
SQLALCHEMY_ECHO: false
JWT_SECRET_KEY: eyJhbGciOiJIUzI1NiJ9
SQLALCHEMY_DATABASE_URI: mysql+pymysql://tester:password@mysql_db:3306/Schedules    # for docker-compose network
SQLALCHEMY_TRACK_MODIFICATIONS: false
TESTING: false
