
FLASK_ENV: development
SQLALCHEMY_ECHO: false
JWT_SECRET_KEY: eyJhbGciOiJIUzI1NiJ9
SQLALCHEMY_DATABASE_URI: mysql+pymysql://tester:password@0.0.0.0:3306/Schedules   # for me
SQLALCHEMY_TRACK_MODIFICATIONS: false
TESTING: true
