FROM python:3.6

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app/

ENV FLASK_ENV="development"  BOOSTER_URL="http://localhost:8080/"

EXPOSE 5000

CMD [ "python", "./stage2.py","runserver" ]