-- -------------------------------------------------------------
-- INSERT
-- -------------------------------------------------------------

-- table : RESOURCE
INSERT INTO public.RESOURCE (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESCRIPTION, RESOURCE_CRITICALITY, RESOURCE_QUANTITY_VALUE, RESOURCE_QUANTITY_DATE, RESOURCE_WARNING_LEVEL, RESOURCE_EMERGENCY_LEVEL) 
VALUES (0, 'water', 'water is an essential element of the life. It comes from the old EARTH planet. DO NOT WASTE IT !', 100, 0.0, now(), 2000.0, 1000.0);
INSERT INTO public.RESOURCE (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESCRIPTION, RESOURCE_CRITICALITY, RESOURCE_QUANTITY_VALUE, RESOURCE_QUANTITY_DATE, RESOURCE_WARNING_LEVEL, RESOURCE_EMERGENCY_LEVEL) 
VALUES (1, 'food', 'food is an essential element of the life. A balanced diet is essential. Eat sugar with precaution !', 90, 0.0, now(), 1500.0, 750.0);
INSERT INTO public.RESOURCE (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESCRIPTION, RESOURCE_CRITICALITY, RESOURCE_QUANTITY_VALUE, RESOURCE_QUANTITY_DATE, RESOURCE_WARNING_LEVEL, RESOURCE_EMERGENCY_LEVEL) 
VALUES (2, 'RESOURCE for triggers tests', 'this resource is to update and to delete (in order to check triggers)', 50, 10.0, now(), 20000.0, 10000.0);

-- table : RESOURCE_VARIATION
INSERT INTO public.RESOURCE_VARIATION (RESOURCE_VARIATION_VALUE, RESOURCE_VARIATION_DATE, RESOURCE_VARIATION_APPLICATION, RESOURCE_VARIATION_DESCRIPTION, RESOURCE_ID) 
VALUES (20.0, now(), FALSE, 'daily production of water', 1);
INSERT INTO public.RESOURCE_VARIATION (RESOURCE_VARIATION_VALUE, RESOURCE_VARIATION_DATE, RESOURCE_VARIATION_APPLICATION, RESOURCE_VARIATION_DESCRIPTION, RESOURCE_ID) 
VALUES (30.0, now(), FALSE, 'daily production of food', 2);
INSERT INTO public.RESOURCE_VARIATION (RESOURCE_VARIATION_VALUE, RESOURCE_VARIATION_DATE, RESOURCE_VARIATION_APPLICATION, RESOURCE_VARIATION_DESCRIPTION, RESOURCE_ID) 
VALUES (-20.0, now(), FALSE, 'for the test of the variation triggers', 3);

-- table : USER_APPLICATION
INSERT INTO public.USER_APPLICATION (USER_APPLICATION_ID, USER_APPLICATION_PROFILE) 
VALUES (0, 'classic');
INSERT INTO public.USER_APPLICATION (USER_APPLICATION_ID, USER_APPLICATION_PROFILE) 
VALUES (1, 'checker');
INSERT INTO public.USER_APPLICATION (USER_APPLICATION_ID, USER_APPLICATION_PROFILE) 
VALUES (2, 'administrator');
INSERT INTO public.USER_APPLICATION (USER_APPLICATION_ID, USER_APPLICATION_PROFILE) 
VALUES (3, 'for test');

-- table : PIONEER
INSERT INTO public.PIONEER (PIONEER_LOGIN, PIONEER_PASSWORD, PIONEER_EMAIL, PIONEER_FIRST_NAME, PIONEER_LAST_NAME, PIONEER_BIRTHDATE, PIONEER_SEX, PIONEER_NOTATION, USER_APPLICATION_ID) 
VALUES ('jto', 'jto_pwd', 'jeantornier@gmail.com', 'jean', 'tornier', TO_TIMESTAMP('1992-03-24 08:30:00', 'YYYY-MM-DD HH24:MI:SS'), FALSE, 100, 3);
INSERT INTO public.PIONEER (PIONEER_LOGIN, PIONEER_PASSWORD, PIONEER_EMAIL, PIONEER_FIRST_NAME, PIONEER_LAST_NAME, PIONEER_BIRTHDATE, PIONEER_SEX, PIONEER_NOTATION, USER_APPLICATION_ID) 
VALUES ('ama', 'ama_pwd', 'audreymartins@yahoo.fr', 'audrey', 'martins', TO_TIMESTAMP('1990-01-10 10:10:00', 'YYYY-MM-DD HH24:MI:SS'), TRUE, 600, 2);
INSERT INTO public.PIONEER (PIONEER_LOGIN, PIONEER_PASSWORD, PIONEER_EMAIL, PIONEER_FIRST_NAME, PIONEER_LAST_NAME, PIONEER_BIRTHDATE, PIONEER_SEX, PIONEER_NOTATION, USER_APPLICATION_ID) 
VALUES ('vga', 'vga_pwd', 'valeriegarcia@wanadoo.fr', 'valerie', 'garcia', TO_TIMESTAMP('1975-06-30 23:55:12', 'YYYY-MM-DD HH24:MI:SS'), TRUE, 750, 2);
INSERT INTO public.PIONEER (PIONEER_LOGIN, PIONEER_PASSWORD, PIONEER_EMAIL, PIONEER_FIRST_NAME, PIONEER_LAST_NAME, PIONEER_BIRTHDATE, PIONEER_SEX, PIONEER_NOTATION, USER_APPLICATION_ID) 
VALUES ('fdu', 'fdu_pwd', 'françoisdupond@gmail.com', 'françois', 'dupond', TO_TIMESTAMP('1989-10-02 08:05:01', 'YYYY-MM-DD HH24:MI:SS'), FALSE, 800, 2);
INSERT INTO public.PIONEER (PIONEER_LOGIN, PIONEER_PASSWORD, PIONEER_EMAIL, PIONEER_FIRST_NAME, PIONEER_LAST_NAME, PIONEER_BIRTHDATE, PIONEER_SEX, PIONEER_NOTATION, USER_APPLICATION_ID) 
VALUES ('jdo', 'jdo_pwd', 'juliendollet@dollet.fr', 'julien', 'dollet', TO_TIMESTAMP('1965-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'), FALSE, 500, 2);
INSERT INTO public.PIONEER (PIONEER_LOGIN, PIONEER_PASSWORD, PIONEER_EMAIL, PIONEER_FIRST_NAME, PIONEER_LAST_NAME, PIONEER_BIRTHDATE, PIONEER_SEX, PIONEER_NOTATION, USER_APPLICATION_ID) 
VALUES ('jbl', 'jbl_pwd', 'julieblanc@gmail.com', 'julie', 'blanc', TO_TIMESTAMP('1989-01-10 02:21:00', 'YYYY-MM-DD HH24:MI:SS'), TRUE, 450, 1);
INSERT INTO public.PIONEER (PIONEER_LOGIN, PIONEER_PASSWORD, PIONEER_EMAIL, PIONEER_FIRST_NAME, PIONEER_LAST_NAME, PIONEER_BIRTHDATE, PIONEER_SEX, PIONEER_NOTATION, USER_APPLICATION_ID) 
VALUES ('bbl', 'bbl_pwd', 'brunoblanc@blanc.fr', 'bruno', 'blanc', TO_TIMESTAMP('1989-03-10 10:12:00', 'YYYY-MM-DD HH24:MI:SS'), FALSE, 400, 1);
INSERT INTO public.PIONEER (PIONEER_LOGIN, PIONEER_PASSWORD, PIONEER_EMAIL, PIONEER_FIRST_NAME, PIONEER_LAST_NAME, PIONEER_BIRTHDATE, PIONEER_SEX, PIONEER_NOTATION, USER_APPLICATION_ID) 
VALUES ('pft', 'pft_pwd', 'pioneerfortest@email.fr', 'pioneer', 'fortest', TO_TIMESTAMP('1975-03-10 10:12:00', 'YYYY-MM-DD HH24:MI:SS'), FALSE, 200, 1);

-- table : BABY_REQUEST
INSERT INTO public.BABY_REQUEST (REQUEST_CREATE_DATE, REQUEST_SUBMIT_DATE, REQUEST_ACCEPT_DATE_1, REQUEST_ACCEPT_DATE_2, REQUEST_REFUSE_DATE_1, REQUEST_REFUSE_DATE_2, REQUEST_SCHEDULE_DATE, REQUEST_CLOSE_DATE, BABY_LOGIN, BABY_PASSWORD, BABY_EMAIL, BABY_FIRST_NAME, BABY_LAST_NAME, BABY_SEX) 
VALUES (TO_TIMESTAMP('2010-03-10 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2011-03-20 08:30:00', 'YYYY-MM-DD HH24:MI:SS'), null, null, null, null, null, null, null, null, null, 'guillaume', 'blanc', null);
INSERT INTO public.BABY_REQUEST (REQUEST_CREATE_DATE, REQUEST_SUBMIT_DATE, REQUEST_ACCEPT_DATE_1, REQUEST_ACCEPT_DATE_2, REQUEST_REFUSE_DATE_1, REQUEST_REFUSE_DATE_2, REQUEST_SCHEDULE_DATE, REQUEST_CLOSE_DATE, BABY_LOGIN, BABY_PASSWORD, BABY_EMAIL, BABY_FIRST_NAME, BABY_LAST_NAME, BABY_SEX) 
VALUES (TO_TIMESTAMP('2000-10-03 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), null, null, null, null, null, null, null, null, null, null, 'celine', 'martins', null);
INSERT INTO public.BABY_REQUEST (REQUEST_CREATE_DATE, REQUEST_SUBMIT_DATE, REQUEST_ACCEPT_DATE_1, REQUEST_ACCEPT_DATE_2, REQUEST_REFUSE_DATE_1, REQUEST_REFUSE_DATE_2, REQUEST_SCHEDULE_DATE, REQUEST_CLOSE_DATE, BABY_LOGIN, BABY_PASSWORD, BABY_EMAIL, BABY_FIRST_NAME, BABY_LAST_NAME, BABY_SEX) 
VALUES (TO_TIMESTAMP('2020-10-10 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2011-03-20 08:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2012-03-20 08:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2013-03-20 08:30:00', 'YYYY-MM-DD HH24:MI:SS'), null, null, TO_TIMESTAMP('2014-03-20 08:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2015-03-20 08:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'tle', 'tle_email', null, 'test', 'le retour', null);

-- table : BABY_PARENT
INSERT INTO public.BABY_PARENT (PIONEER_ID, REQUEST_ID) 
VALUES (6, 1);
INSERT INTO public.BABY_PARENT (PIONEER_ID, REQUEST_ID) 
VALUES (7, 1);
INSERT INTO public.BABY_PARENT (PIONEER_ID, REQUEST_ID) 
VALUES (2, 2);
INSERT INTO public.BABY_PARENT (PIONEER_ID, REQUEST_ID) 
VALUES (3, 2);

-- table : BABY_CHECKERS
INSERT INTO public.BABY_CHECKERS (PIONEER_ID, REQUEST_ID) 
VALUES (1, 1);
INSERT INTO public.BABY_CHECKERS (PIONEER_ID, REQUEST_ID) 
VALUES (2, 1);
INSERT INTO public.BABY_CHECKERS (PIONEER_ID, REQUEST_ID) 
VALUES (3, 2);
INSERT INTO public.BABY_CHECKERS (PIONEER_ID, REQUEST_ID) 
VALUES (4, 2);
INSERT INTO public.BABY_CHECKERS (PIONEER_ID, REQUEST_ID) 
VALUES (5, 2);

-- -------------------------------------------------------------
-- UPDATES
-- -------------------------------------------------------------

-- table : RESOURCE
UPDATE public.RESOURCE SET RESOURCE_NAME = 'new RESOURCE update for triggers' WHERE RESOURCE_ID = 3;
UPDATE public.RESOURCE SET RESOURCE_DESCRIPTION = 'this is a new description of the resource (name changed also previously)' WHERE RESOURCE_ID = 3;
UPDATE public.RESOURCE SET RESOURCE_CRITICALITY = 40 WHERE RESOURCE_ID = 3;
UPDATE public.RESOURCE SET RESOURCE_QUANTITY_VALUE = 20.0 WHERE RESOURCE_ID = 3;
UPDATE public.RESOURCE SET RESOURCE_QUANTITY_DATE = now() WHERE RESOURCE_ID = 3;
UPDATE public.RESOURCE SET RESOURCE_WARNING_LEVEL = 20100.0 WHERE RESOURCE_ID = 3;
UPDATE public.RESOURCE SET RESOURCE_EMERGENCY_LEVEL = 10100.0 WHERE RESOURCE_ID = 3;

-- table : RESOURCE_VARIATION
UPDATE public.RESOURCE_VARIATION SET RESOURCE_VARIATION_VALUE = -30.0 WHERE RESOURCE_VARIATION_ID = 3;
UPDATE public.RESOURCE_VARIATION SET RESOURCE_VARIATION_DATE = now() WHERE RESOURCE_VARIATION_ID = 3;
UPDATE public.RESOURCE_VARIATION SET RESOURCE_VARIATION_APPLICATION = TRUE WHERE RESOURCE_VARIATION_ID = 3;
UPDATE public.RESOURCE_VARIATION SET RESOURCE_VARIATION_DESCRIPTION = 'new description of the resource variation (for the update).' WHERE RESOURCE_VARIATION_ID = 3;
UPDATE public.RESOURCE_VARIATION SET RESOURCE_ID = 2 WHERE RESOURCE_VARIATION_ID = 3;

-- table : USER_APPLICATION
UPDATE public.USER_APPLICATION SET USER_APPLICATION_PROFILE = 'new label' WHERE USER_APPLICATION_ID = 3;

-- table : PIONEER
UPDATE public.PIONEER SET PIONEER_LOGIN = 'new_login' WHERE PIONEER_ID = 8;
UPDATE public.PIONEER SET PIONEER_PASSWORD = 'new_pwd' WHERE PIONEER_ID = 8;
UPDATE public.PIONEER SET PIONEER_EMAIL = 'new_email' WHERE PIONEER_ID = 8;
UPDATE public.PIONEER SET PIONEER_FIRST_NAME = 'new_first_name' WHERE PIONEER_ID = 8;
UPDATE public.PIONEER SET PIONEER_LAST_NAME = 'new_last_name' WHERE PIONEER_ID = 8;
UPDATE public.PIONEER SET PIONEER_BIRTHDATE = TO_TIMESTAMP('1900-01-01 01:01:01', 'YYYY-MM-DD HH24:MI:SS') WHERE PIONEER_ID = 8;
UPDATE public.PIONEER SET PIONEER_SEX = TRUE WHERE PIONEER_ID = 8;
UPDATE public.PIONEER SET PIONEER_NOTATION = 800 WHERE PIONEER_ID = 8;
UPDATE public.PIONEER SET USER_APPLICATION_ID = 2 WHERE PIONEER_ID = 8;

-- table : BABY_REQUEST
UPDATE public.BABY_REQUEST SET REQUEST_CREATE_DATE = TO_TIMESTAMP('2000-01-01 01:01:01', 'YYYY-MM-DD HH24:MI:SS') WHERE REQUEST_ID = 3;
UPDATE public.BABY_REQUEST SET REQUEST_SUBMIT_DATE = TO_TIMESTAMP('2000-01-01 01:01:02', 'YYYY-MM-DD HH24:MI:SS') WHERE REQUEST_ID = 3;
UPDATE public.BABY_REQUEST SET REQUEST_ACCEPT_DATE_1 = TO_TIMESTAMP('2000-01-01 01:01:03', 'YYYY-MM-DD HH24:MI:SS') WHERE REQUEST_ID = 3;
UPDATE public.BABY_REQUEST SET REQUEST_ACCEPT_DATE_2 = TO_TIMESTAMP('2000-01-01 01:01:04', 'YYYY-MM-DD HH24:MI:SS') WHERE REQUEST_ID = 3;
UPDATE public.BABY_REQUEST SET REQUEST_REFUSE_DATE_1 = TO_TIMESTAMP('2000-01-01 01:01:05', 'YYYY-MM-DD HH24:MI:SS') WHERE REQUEST_ID = 3;
UPDATE public.BABY_REQUEST SET REQUEST_REFUSE_DATE_2 = TO_TIMESTAMP('2000-01-01 01:01:06', 'YYYY-MM-DD HH24:MI:SS') WHERE REQUEST_ID = 3;
UPDATE public.BABY_REQUEST SET REQUEST_SCHEDULE_DATE = TO_TIMESTAMP('2000-01-01 01:01:07', 'YYYY-MM-DD HH24:MI:SS') WHERE REQUEST_ID = 3;
UPDATE public.BABY_REQUEST SET REQUEST_CLOSE_DATE = TO_TIMESTAMP('2000-01-01 01:01:08', 'YYYY-MM-DD HH24:MI:SS') WHERE REQUEST_ID = 3;
UPDATE public.BABY_REQUEST SET BABY_LOGIN = 'new_baby_login' WHERE REQUEST_ID = 3;
UPDATE public.BABY_REQUEST SET BABY_PASSWORD = 'new_baby_password' WHERE REQUEST_ID = 3;
UPDATE public.BABY_REQUEST SET BABY_EMAIL = 'new_baby_email' WHERE REQUEST_ID = 3;
UPDATE public.BABY_REQUEST SET BABY_FIRST_NAME = 'new_baby_first_name' WHERE REQUEST_ID = 3;
UPDATE public.BABY_REQUEST SET BABY_LAST_NAME = 'new_baby_last_name' WHERE REQUEST_ID = 3;
UPDATE public.BABY_REQUEST SET BABY_SEX = FALSE WHERE REQUEST_ID = 3;

-- table : BABY_PARENT
UPDATE public.BABY_PARENT SET PIONEER_ID = 4 WHERE BABY_PARENT_ID = 4;
UPDATE public.BABY_PARENT SET REQUEST_ID = 1 WHERE BABY_PARENT_ID = 4;

-- table : BABY_CHECKERS
UPDATE public.BABY_CHECKERS SET PIONEER_ID = 6 WHERE BABY_CHECKERS_ID = 5;
UPDATE public.BABY_CHECKERS SET REQUEST_ID = 1 WHERE BABY_CHECKERS_ID = 5;